const socket = io();
let currentRoom = null;
let isHost = false;

// ALL 400 QUESTIONS INTEGRATED
const QUESTIONS = [
    "1. Birthday", "2. Worst mistake", "3. Ur greatest fear", "4. Crush", "5. Best colour", 
    "6. Do u or have u smoked?", "7. Do u drink alcohol?", "8. Do u go for nyt parties?", 
    "9. Last time u cried and wat caused it", "10. Ur dreams", "11. Have u or do u maturate?", 
    "12. Happiest moment", "13. Best memory", "14. Last kiss and wit who", "15. Do you watch porn?", 
    "16. Your best body part", "17. Ever been fucked hard nd u cried?", "18. Complete d**k", 
    "19. Complete p***y", "20. Ur most enjoyable sex, tel me abt it in details", "21. Full name", 
    "22. If u have d chance wil u date me?", "23. Will u kiss me?", "24. Kiss or hug", 
    "25. Favorite song", "26. Favorite movie", "27. Ever kissed a same gender person?", 
    "28. Do u love bj?", "29. Send me ur number", "30. Ever maked out?", "31. Wanna explore me?", 
    "32. Wanna kiss me?", "33. Wanna fuck me?", "34. Wanna date me?", "35. Ever been abused?", 
    "36. Best hubby", "37. Tel me 3 deepest secrets", "38. Send me ur nude pics or porn videos", 
    "39. Favorite body part of ur opposite gender", "40. Big dicks or normal dicks", 
    "41. Big pussy or normal pussy", "42. Promise to kiss me wen we meet", 
    "43. Tell me how u really feel about me", "44. Tell me a story", "45. Do u wear bra?", 
    "46. Do u always wear pant?", "47. Promise to watch porn wit me or gv me a Bj", 
    "48. Will u let me finger u or stroke ur dick?", "49. Wat age did u have ur first sex", 
    "50. Wat year did u have ur first sex", "51. Player or loyal", "52. Single or taken", 
    "53. Have you ever been played?", "54. Have you ever played someone?", "55. Tell me an erotic story", 
    "56. Last sex", "57. Ever had sex wit a same gender person?", "58. Use my pic as ur dp for 1 week", 
    "59. Send me ur breast or chest picture", "60. Do u sex chat?", "61. If u see me naked, wat will u do", 
    "62. Shy or bold", "63. Ever slept naked?", "64. Virgin?", "65. Wat turns u on", 
    "66. What do you love doing the most", "67. Ever begged for sex?", "68. D craziest tin u have ever done", 
    "69. Best friend", "70. Ever had sex?", "71. Age", "72. Are you naughty?", 
    "73. Naughtiest tin u have ever done", "74. Ever exchanged nude?", "75. Buy me a gift", 
    "76. Wil you let me touch you?", "77. Do you love me?", "78. How do you want d dick or pussy to be.", 
    "79. Sex chat with me", "80. Have some mistakenly seeing ur dick or pussy?", "81. What gets u wet", 
    "82. Last time u felt like having sex", "83. Favorite clothes", "84. Ask me anything", 
    "85. Promise to have sex with me", "86. Nickname", "87. Favorite sex position", 
    "88. How long do you want sex to be.", "89. Do you love sex?", "90. Something u will change about yourself", 
    "91. Send me two of your sexiest pics", "92. Tell me how you had ur last time sex in details", 
    "93. How much do you enjoy sex", "94. Tell me things you want from me.", "95. Hard fuck or normal", 
    "96. Send me 2 pics of your dick", "97. Send me 2 pics of your pussy", "98. Hairy dick/pussy or shaved", 
    "99. Send me your dance videos", "100. Will you fuck me?", "101. Ever fucked someone you don't love?", 
    "102. What do you like in a girl", "103. What do you like in a boy", "104. Tell me things you want us to do together", 
    "105. Send me a sex video of yourself", "106. How much do you love sex.", 
    "107. Do you prefer being sucked on your pussy or rather have sex.", "108. Are you horny right now", 
    "109. Do you prefer being sucked on your dick or rather have sex", "110. kiss each other for a whole minute", 
    "111. will you give me a lap dance", "112. what is your favorite body part on a girl?", 
    "113. which do you prefer wet or dry kiss", "114. what is your favorite body part on a boy", 
    "115. have you ever had a sex dream", "116. what on your mind right now", "117. will you come over my place", 
    "118. if we were both inside the room what will you do to me?", "119. What don’t you like about me?", 
    "120. Did you like your first kiss?", "121. Have you ever decided to kiss or make out with a guy just because you were Horny?", 
    "122. Which do you like the most, your boobs or your bum?", "123. What are you wearing right now?", 
    "124. If you ask me to do something naughty what would you prefer I do?", "125. Missionary or doggy-style?", 
    "126. What turns you on the most in a guy?", "127. Is it okay if I kiss you?", 
    "128. How you react if I kissed you immediately I see you next time?", "129. How did you get so beautiful?", 
    "130. Assuming we were stuck together alone in a house for a whole day, what do you think we would do?", 
    "131. What color of panties do you prefer and why?", "132. What is the color of the underpants you are wearing right now?", 
    "133. Are you a boobs or ass man?", "134. Where you do like being touched the most?", 
    "135. Have you ever thought about kissing me?", "136. What if I was naked and laying in your bed?", 
    "137. Do you want to help keep my body warm?", "138. How long do you think a guy should last on bed?", 
    "139. Do you like cooking?", "140. Who is your favorite celebrity?", "141. Have you ever had a crush on one of your cousins?", 
    "142. What is your worst habit?", "143. Have you ever dated two girls at the same time?", 
    "144. While you are kissing, what types of other things you prefer to be done simultaneously?", 
    "145. Did you know I can make you shake all over if you let me rub my cap on your clit?", 
    "146. What do my lips taste like?", "147. How do you feel about being fingered?", 
    "148. Where do you like it best? Back or front?", "149. Where is somewhere in my house you would like to have sex in apart fro the bedroom?", 
    "150. Do you want me to talk dirty?", "151. Show me a porn video you’d want us to act out together", 
    "152. Try not to get turned on while I sit on your lap and kiss your neck for 60 seconds.", 
    "153. Would you rather spank someone or be spanked?", "154. Kiss my nipple for 60 seconds.", 
    "155. What’s your biggest sexual fear?", "156. If you had to fuck one animal, what animal would you pick?", 
    "157. Do you love me? How much?", "158. Would you take a shower with me?", 
    "158. How often do you watch something naughty?", "159. How often do you trim down there?", 
    "160. How many people have seen you naked?", "161. What are you wearing?", "162. What’s something you want me to do to you?", 
    "163. Wide or tight p***y", "164. How many kids would you like to have?", 
    "165. Twerk on my lap with only your underwear", "166. wanna suck my pussy?", "167. wanna suck my dick?", 
    "168. Do you prefer rough or slow sex?", "169. Do you like your partner to be silent or loud?", 
    "170. Have you ever cheated in an exam?", "171. When was the first time that you watched porn?", 
    "172. Tell me a Dirty Truth about you that no one else knows?", "173. Do you think I’m Hot?”", 
    "174. Who would you most like to make out with?", "175. When is the last time that you touched yourself?", 
    "176. Do you ever walk around in public without any underwear on?", 
    "177. What do you think is the absolutely sexiest part of my body?", 
    "178. If I was tied down to the bed right now, what would you do to me?", 
    "179. Have you ever accidentally grabbed someones butt?", "180. Name one celebrity you would want to make out with", 
    "181. When was the last time you masturbated?", "182. Do you like to listen to music while having sex?", 
    "183. Kiss me passionately?", "183. Tell me how you would make love to me.", 
    "184. Tell me something to get me aroused.", "185. Does naughty talk get you aroused?", 
    "186. Have you ever witnessed people having sex?", "187. which do u prefer, fuck through panties? or fuck without panties?", 
    "188. will u romance me without being asked?", "189. Call me and say 'I Love You' along with my name as loud as you can.", 
    "190. Do you prefer texting me or talking to me on the phone?", "191. If you were famous, what would you be famous for?", 
    "192. if I was in the mood for sex, will u give it to me?", "193. What’s one thing you can’t live without?", 
    "194. What’s the last thing you searched on your phone?", "195. Of the people in this room, who do you most want to make out with?", 
    "196. What’s your biggest sexual fear?", "197. if your p***y was the key to my success will you give it to me", 
    "198. How do you really feel about sex?", "199. How would you feel if my dick was on your pussy right now?", 
    "200. Do you think my pussy will be sweeter than honey", "201. Do you think my dick wil be sweeter than honey", 
    "202. Hw will u feel if my p***y was on your dick right now?", "203. Do u prefer skin to skin or condom?", 
    "204. Do you like being lick on your pussy while sex is going on", 
    "205. If u were to choose a sex time for both of us, how long will that be?", "206. Do I make u nervous", 
    "207. What is your position on premarital sex?", "208. Tell me one thing I could do that would make you immediately orgasm.", 
    "209. What is your favorite body part for me to suck on?", 
    "210. Would you prefer to dominate me in bed or do you want me to dominate you in bed?", 
    "211. Which is your favorite kind of sex: soft, slow, and sweet or aggressive, fast, and feisty?", 
    "212. If we could only have sex in one position for a month, what position would you pick pussy or ass", 
    "213. Is there something you've seen in a steamy movie that you'd like to try?", 
    "214. What do you think is the sexiest part of your body is?", "215. Would you consider yourself flexible (in bed)?", 
    "216. Why did you break up with your last boyfriend or girlfriend?", "217. What position have you always wanted to try?", 
    "218. What do you wish we did in the bedroom?", "219. Where do you love to have sex?", 
    "220. If you could have sex in any location in the world, where would it be?", 
    "221. Where, and how, can I touch you that will turn you on?", "222. Hw will u like to be sex on your first sex", 
    "223. If I was with you, which part of my body would you want to lick first?", 
    "224. If I was with you right now, what would you do with me?", 
    "225. If u were asked to give me a sex position, were will that be p***y or ass?", 
    "226. Name three things you will like to do during sex.", "227. Hw many times a week would you want to have sex?", 
    "228. Do you think it’s possible to have a friend with benefits?", 
    "229. If I allowed you to do anything to me what would you do?", "230. How much do you like dirty talk?", 
    "231. How will you take it if I put my hand underneath your shirt right now?", 
    "232. What color of underwear do you think I am wearing right now?", 
    "233. How likely will you allow me to touch you down there?", "234. Have you ever wanted to tear my clothes off?", 
    "235. Which position is your favorite for us?", 
    "236. If you could choose anything on my body to see right now what would it be?", 
    "237. What is the difference to you between sex and making love?", "238. What’s your secret move to turn a guy on?", 
    "239. What should a guy do to make you wet?", "240. Did you ever felt hot in shower while rubbing your body?", 
    "241. Do you like your boobs being pressed?", "242. Can you tell me some reasons why I like you?", 
    "243. Do you miss me right now?", "244. Is there anything you’re too nervous to tell me in person?", 
    "245. Do you want to see me without my shirt on?", "246. Wat part of your body will you let me touch?", 
    "247. Would u like to be kissed while having sex?", "248. Name the sex position you would like us to try?", 
    "249. Hw many sex position do you know?", "250. Are you a jealous person", 
    "251. Have someone ever make an attempt to have sex with you?", 
    "252. Would you like me to be the person that will disvirgins you?", 
    "253. How would you feel if someone sends u pron?", "254. At wat age do u plan to get married?", 
    "255. How long can u last in bed? Would you like me to be the person that will disvirgins you?", 
    "256. Do u discuss your relationship with your friends?", "257. Wat do u feel like when sex is on your mind?", 
    "258. Do you think we’d do something funny if we get drunk together?", "259. Do you think you’re a good kisser?", 
    "260. Where on your body would you like me to massage?", "261. What would you do if I come to you naked?", 
    "262. What would you ask me to do for you if I were naked right now?", "263. Can you take my panties off with just your teeth?", 
    "264. How would you start with me if I was in your bed right now?", 
    "265. What would you do if we were home alone naked together?", 
    "266. What would you like to hear from me while we do it?", 
    "267. If you could only feel me in one place, where would it be?", 
    "268. If you are still a virgin, how would you demand it?", "269. Have you ever been seduced by someone?", 
    "270. Would you ever want to play dirty with me?", "271. Do u like me being ontop u or u being ontop me?", 
    "272. Do you like it when I pull your hair during sex?", "273. Are u a dick sucker", 
    "274. How can I make sex more enjoyable for you?", 
    "275. Does knowing that people can hear us having sex turn you on?", 
    "276. Do you consider yourself a naughty girl? If yes, prove it.", 
    "277. What is the one thing you can never resist and that instantly gets you wet?", 
    "278. Would you have sex with me while somebody is watching us?", 
    "279. Would you make out with another girl while I watch?", "280. Would you like it if I sent you naked pictures of me?", 
    "281. Are you confident about showing your naked body?", "282. Have you ever been hot for a teacher?", 
    "283. are you a shy guy, sexually?", "284. Would you prefer my dick deep inside your pussy or at the bottom?", 
    "285. What part of my body would you want me to tattoo?", "286. have you ever stared at my butt or chest?", 
    "287. Is laughing in sex okay, or it has to be serious?", "289. Have you ever tried edible underwear?", 
    "290. Do you like experimenting with different positions, or your favorite?", 
    "291. If you could choose anything on my body to see right now what would it be?", 
    "292. Which part of guys body you want to touch or feel?", "293. Have you ever kissed a girl?", 
    "294. How many minutes should my d**k or p***y should stay inside yours without removing it?", 
    "295. Wanna fuck my ass or pussy?", "296. Do you prefer to take the lead for sex?", 
    "297. What do you think is the sexiest thing about my body?", "298. How do you like to be touched by me?", 
    "299. How would you start with me if I was in your bed right now?", "300. Can I watch you play with your stuff", 
    "301. Do u have a condom?", "302. Figure out how my pussy will looks like", 
    "303. Figure out how my dick wii looks like", 
    "304. If I was home alone and I ask for sex will u let me placed my dick on your pussy?", 
    "304. If sex was wat I asked as a birthday gift will u give it to me?", 
    "305. Do u think your mom was a virgin when your dad met her?", 
    "306. If we were to have sex will u let any one knows about it?", 
    "307. Do u prefer being sucked on your pussy before sex?", 
    "308. Do u prefer being sucked on your dick before sex?", "309. What do you want sex, romance, wet kiss?", 
    "310. What should I say if I wanted sex from u?", "311. Wat would you say if I said I wanted sex?", 
    "312. if we were both shy for sex mood, hw Would u make mi interested,?", "313. Who was your first girlfriend", 
    "314. What turns you on most during sex?", "315. How many times have you been in love?", 
    "316. Who are your ex-girlfriends, (if any) and what made the relationship end as it did?", 
    "317. Have you ever lied to me?", "318. Will u be surprised if I ask u for sex?", 
    "319. Last time you had a wet dream?", "320. How will it feel like to lose your virginity?", 
    "321. Would you ever watch porn with a girl?", "322. What would you do if I put my hands under your shirt?", 
    "323. If you are still a virgin, what do you want your first time to be like?", "324. Do you like to be loud during s..x?", 
    "325. Do you like it when I don’t wear any underwear?", "326. Do you want to cuddle with me?", 
    "327. What is your favorite position when you are on top?", "328. Would you ever want to be blindfolded during sex?", 
    "329. What is the quickest that you think you can undress me?", 
    "330. Do you think you can get naked in less than 5 seconds during sex?", 
    "331. Do you like to do it with clothes on or off?", "332. Do you want to spank me?", 
    "333. Your lips look lonely. Do you want my lips to keep them company?", "334. Do you think that I can handle you?", 
    "335. Do you like being naked or are you shy about it?", 
    "336. If you realized that someone was watching you have s..x, would you stop or would you keep going?", 
    "337. Is there anything that you would not do in bed?", "338. How long will it take you to get over here and into my pants?", 
    "339. What is the sexiest outfit that you can think of?", 
    "340. Does talking dirty turn you on, and do you want to try it with me?", 
    "341. Are you into phone sex, and do you want to try it?", 
    "342. What is the thing that makes you feel good the most during sex?", 
    "343. Do you like foreplay or do you like going straight to business?", "344. Do you like it when I come inside you?", 
    "335. Do you like to watch me as I change clothes?", "336. Do you like it when I touch you slowly all over your body?", 
    "337. Which part of me do you miss the most right now?", "338. If we only had 20 minutes together, what would we do?", 
    "339. Does thinking about me make you wet?", "340. How long should foreplay take before sex?", 
    "341. Describe to me in detail what it feels like when I’m inside you.", "342. Do you like it when I tell you what to do?", 
    "343. What is a sure way to turn you on within seconds?", "344. Do you prefer younger or older men?", 
    "345. Are you enjoying these flirty questions?", "346. When was the last time you jerked off thinking of me?", 
    "347. Do you like it when I make the first move?", "348. Do you have a name for your thing and what is it?", 
    "349. Do you get an instant erection when you see someone naked?", 
    "350. If you had to choose between getting head or having sex, which would you pick?", 
    "351. Do you think I’m sexy?", "352. What is your favorite thing to do with my body?", 
    "353. Do you like it when people can hear us having sex?", "354. When are u coming to sex me?", 
    "355. When am I coming to make u feed good?", 
    "356. If u were shy to ask for the sex while we are inside, will u tell me through your phone?", 
    "357. Do u like condom to be fixed in your presence or your obsence?", "358. Do you think my dick will enter your pussy?", 
    "359. If your p***y was so tight for my d**k, wat will u do when u are in the mood?", 
    "360. If you were crying while I was penetrating should I stop?", 
    "361. If my dick was on your pussy, were should I put my hands when sex is going on?", 
    "362. Which do you prefer, eyes opend, or eyes closed while having sex?", 
    "363. Will u Send me a photo of how my dick should be inside your p***y", 
    "364. Will u Send me a photo of how my p***y should be inside your d**k", 
    "365. When was a time you were so turned on you couldn’t stand it?", "366. Do you ever just want to tear off my clothes?", 
    "367. Would you prefer to see me in hot pants or a short skirt?", "368. Will u like it if I fuck you for 2 minutes?", 
    "369. How do you like your breasts and nipples played with?", "370. When did you first learn about sex?", 
    "371. How much eye contact do you like to have during sex?", "372. What's the sexiest movie you've ever watched?", 
    "373. What’s your favorite pair or underwear?", "374. Using three words, how do you feel about me?", 
    "375. How do you want me?", "376. Would you like to know how I feel about you?", 
    "377. Where would you like to have sex My place or yours?", "378. If I was at your window right now, would you invite me in?", 
    "379. If you could kiss me goodnight every night, would you?", 
    "380. Would you like the cap of my dick being robbed on your pussy before entering?", 
    "381. Would you be loud or quiet during sex?", "382. Do you prefer to take control or be submissive?", 
    "383. What would you like me to do more in bed?", "384. Is your ass soft ?", 
    "385. What is your favorite position when you are on top?", "386. What is your favorite kind of kiss?", 
    "387. Do you like when I take you in deep or when you take me in deep?", "388. Will you like it when I touch you there?", 
    "389. Have u ever felt horny while texting on the phone?", "390. Who was the first girl that touch your dick?", 
    "391. who was the first boy that touch your ass?", "392. Which girl do u think would give you the best sex?", 
    "393. Should u prefer we watch pron before sex?", "394. Which boy do u think would give you the best sex?", 
    "395. Who do u fantasize when u think about sex?", "396. Have you ever gone a whole day without wearing underwear?", 
    "397. What would you do if I answered the door naked?", 
    "398. If I was sexing u and my dick drove out from your pussy, will u put it back ur self, or should I be the one to put it back my self?", 
    "399. Will u be mad if I already made u wet by robbing my dick ontop your pussy and didn't do any tin?", 
    "400. Will u like your breast to be sucked while fucking?"
];

function showScreen(id) {
    document.querySelectorAll('.screen').forEach(s => s.style.display = 'none');
    document.getElementById(id).style.display = 'block';
}

document.getElementById('btn-create').onclick = () => { isHost = true; socket.emit('create-room'); };
document.getElementById('btn-join').onclick = () => {
    const val = document.getElementById('join-input').value;
    if(val) socket.emit('join-room', val);
};

socket.on('room-created', (id) => {
    currentRoom = id;
    document.getElementById('room-display').innerText = "CODE: " + id;
});

socket.on('game-start', () => { if(isHost) showScreen('screen-modes'); });

function setMode(mode) { socket.emit('select-mode', { roomId: currentRoom, mode: mode }); }

socket.on('mode-set', () => {
    showScreen('screen-game');
    const container = document.getElementById('card-container');
    container.innerHTML = '';
    // Show 20 cards at a time to keep it clean
    for(let i=1; i<=20; i++) {
        let card = document.createElement('div');
        card.className = 'card'; card.innerText = i;
        card.onclick = () => {
            const q = QUESTIONS[Math.floor(Math.random() * QUESTIONS.length)];
            socket.emit('flip-card', { roomId: currentRoom, question: q });
        };
        container.appendChild(card);
    }
});

socket.on('card-flipped', (data) => {
    document.getElementById('question-text').innerText = data.question;
    document.getElementById('question-display').style.display = 'flex';
});

function closeQuestion() { document.getElementById('question-display').style.display = 'none'; }
